vertex.allow-user-move=true
vertex.radius=10
vertex.shape=circle
vertex.tooltip=true
vertex.label=true

edge.tooltip=true
edge.label=true
edge.arrow=true

layout.repulsive-force=50000
layout.attraction-force=10
layout.attraction-scale=50